### ISSUE TITLE
How is dotnet-script different from csi?

### ISSUE THREAD

**Issue by giggio** [dotnet-script/dotnet-script#371]
I don't understand what the difference is. It would be nice to add it to the docs so I know what additional value I am getting with the tool.

**Comment by MarkMichaelis** [comment]
I also have this question.

**Comment by WalkerCodeRanger** [comment]
How about a link to csi for people (like me) that don't know what you're talking about?

**Comment by atifaziz** [comment]
@giggio, @MarkMichaelis Two things that quickly jump to mind: C# Interactive (`csi`) does not support [referencing NuGet packages via the `#r` directive](https://github.com/filipw/dotnet-script#nuget-packages-1) and [interactive debugging](https://github.com/filipw/dotnet-script#debugging).

See also:

- [Integrate csi to dotnet cli](https://github.com/dotnet/roslyn/issues/17666) (dotnet/roslyn#17666)
- [integrate csi with dotnet cli and test it works or coreclr](https://github.com/dotnet/roslyn/issues/6882) (dotnet/roslyn#6882)

Both of the above issues have not moved much whereas this project is quite actively maintained.
