### ISSUE TITLE
Is it possible to reference System packages without using nuget?

### ISSUE THREAD

**Issue by Metrowerks** [dotnet-script/dotnet-script#499]
- If I use nuget reference, I wouldn't be able to run my script with csi:
`#r "nuget: System.DirectoryServices"`
 It will give me error
_"error CS0006: Metadata file 'nuget: System.DirectoryServices' could not be found"_

- If I don't use nuget reference, my csx file will work with csi but it won't work with dotnet-script:
`#r "System.DirectoryServices"`
 It will give me error
_error CS0006: Metadata file 'System.DirectoryServices.AccountManagement' could not be found_

Would it be possible to make my references consistent and work for both csi and dotnet-script? For example, not using nuget with #r for System packages like System.DirectoryServices

**Comment by Lazuplis-Mei** [comment]
> It actually suppost reference system libraries.
```cs
#r "C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-preview8-28405-07\System.Windows.Forms.dll"
#r "C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-preview8-28405-07\System.Drawing.Common.dll"
#r "C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-preview8-28405-07\Accessibility.dll"
#r "C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-preview8-28405-07\Microsoft.Win32.SystemEvents.dll"
using System.Windows.Forms;
Form form = new Form();
form.ShowDialog();
```
> But you need to enter the full path of the library.
