### ISSUE TITLE
How to use dotnet script within Visual Studio/Rider?

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [dotnet-script/dotnet-script#562]
How to use `dotnet script` tool within `Visual Studio`/`Rider`? I mean by it writing scripts without interacting with terminal.

**Comment by seesharper** [comment]
Language services such as intellisense are only provided by editors that are powered by OmniSharp. Check out Visual Studio Code with the C# extension

**Comment by seesharper** [comment]
Answered here 
https://github.com/dotnet-script/dotnet-script/issues/737#issuecomment-1745735931
