### ISSUE TITLE
Question: How to access content files in NuGet packages

### ISSUE THREAD

**Issue by JulianBirch** [dotnet-script/dotnet-script#639]
I'm looking to use dotnet script as a configuration orchestrator where various NuGet packages contain their own config files included as content, but to do this I need to access the content files within the nuget packages. Is there an easy way of doing this?

**Comment by seesharper** [comment]
There is nothing in `dotnet-script` that will help you out here.  My advice is to look to the NuGet libraries, There you can find utilities for reading and creating packages from code. 
https://github.com/NuGet/NuGet.Client
