### ISSUE TITLE
Assembly version issue

### ISSUE THREAD

**Issue by intrasight** [dotnet-script/dotnet-script#648]
Hi,

Since Google implied that it's related to assembly resolution, I'm posting a link here to the issue that I reported

https://github.com/googleapis/google-api-dotnet-client/issues/2009

My references:

<pre>
#r "nuget: Google.Apis, 1.55.0"
#r "nuget: Google.Apis.Core, 1.55.0"
#r "nuget: Google.Apis.Auth, 1.55.0"
#r "nuget: Google.Apis.AnalyticsReporting.v4, 1.55.0"
#r "nuget: Newtonsoft.Json, 13.0.1"
</pre>

I get error:

Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (0x80131621)

**Comment by seesharper** [comment]
Could you try executing the script with `--isolated-load-context`

**Comment by intrasight** [comment]
That did the trick. I just read this for context:

https://www.strathweb.com/2021/09/dotnet-script-1-2-is-out-with-assembly-isolation-feature/

**Comment by georgiosd** [comment]
Looks like I stumbled upon the same! https://github.com/filipw/dotnet-script/issues/663

**Comment by SamVanheer** [comment]
I take it this is the same reason why referencing a NuGet package like `NuGet.Versioning` causes `Object reference not set to an instance of an object` errors? Dotnet-script loads this during script execution, probably when restoring packages.

When a script tries to pass a `SemanticVersion` object to another package that references `NuGet.Versioning` that error occurs. It looks like my local version is `6.0.2` whereas the package being referenced is version `6.1.0`.

#637 mentions difficulties using isolated contexts, but doesn't specify what those difficulties are.  Why isn't full isolation the default?

**Comment by seesharper** [comment]
Closed as resolved with `--isolated-load-context`

**Comment by hrumhurum** [comment]
> #637 mentions difficulties using isolated contexts, but doesn't specify what those difficulties are. Why isn't full isolation the default?

Not all parts of .NET were ready for assembly isolation as of .NET 5.0 when this feature was first implemented. I don't remember the particulars, but there were omissions in assembly loading context during some reflection operations. This caused some packages to fail. Probably we should review the default setting for isolated load context after .NET 8.0 is released, as there is a great chance that outstanding issues in .NET had been already fixed.

**Comment by seesharper** [comment]
@hrumhurum I think `Assembly.LoadFrom` was one of the scenarios where interception did not work.

**Comment by seesharper** [comment]
@hrumhurum I have a branch here that runs all tests in isolated load context. It is just one failing test (ShouldHandlePackageWithNativeLibraries). It is a test that also loads native dll's
https://github.com/dotnet-script/dotnet-script/tree/default-isolation-context
Maybe you want to have a look at it. We consider making this the default in the next major version

**Comment by hrumhurum** [comment]
@seesharper I'll give it a shot. I'll post the results here.

**Comment by seesharper** [comment]
Thanks ❤️

**Comment by hrumhurum** [comment]
@seesharper When I try to run tests in https://github.com/dotnet-script/dotnet-script/tree/default-isolation-context branch, `ShouldHandlePackageWithNativeLibraries` test passes with ok result, no failure observed. Any hints?
