### ISSUE TITLE
Omnisharp issues with generated project

### ISSUE THREAD

**Issue by dewinterjack** [dotnet-script/dotnet-script#651]
I am running the generated project from `dotnet script init`, only adding a dependency.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/17269242/145638412-f3271b71-66ce-4e57-8da1-e85bcf5fd473.png">

I've seen some scripts set the framework at the top but I assume this is correct as that is how it was generated for me. What can I do about these errors? 

When I add the dependency I restart omnisharp, it recognises the dependency for a moment and then these errors appear.

This is on a Mac and the script runs fine I just don't know why vscode and omnisharp is having issues

**Comment by filipw** [comment]
At the moment there is a mismatch between latest .NET 6 dotnet-script and current version of OmniSharp. It will be fixed soon, hopefully in the next OmniSharp release

**Comment by filipw** [comment]
This was resolved in OmniSharp.
