### ISSUE TITLE
Add syntax highlight and code completion to CLI

### ISSUE THREAD

**Issue by iSeiryu** [dotnet-script/dotnet-script#656]
Is it possible to add those features? Even at some basic level.
I found this tool that already implemented those features https://github.com/waf/CSharpRepl. It uses https://github.com/waf/PrettyPrompt to do its CLI magic.

It could be an additional flag to load that functionality:
```bash
dotnet-script -i --syntax-highlight --code-completion
```

If there is a possibility of implementing either of those things we could split them into 2 separate issues.

**Comment by seesharper** [comment]
This is out of the scope of this project I am afraid. We use [Omnisharp](https://github.com/OmniSharp/omnisharp-roslyn) for providing language support like Intellisense.

**Comment by iSeiryu** [comment]
@amine-aboufirass I switched to https://github.com/waf/CSharpRepl. It's fast and has those features enabled by default.
