### ISSUE TITLE
Weird problem under Windows Sandbox

### ISSUE THREAD

**Issue by kasajian** [dotnet-script/dotnet-script#675]
I tried running this in a clean VM, and ran into some weird problems.  

Based on this Web article, I am assuming the latest version supports .NET 6:
https://www.strathweb.com/2021/11/dotnet-script-1-3-is-out-with-net-6-0-support/#more-6740

Looks like it's looking for .NET 3.1.  That's also what the front of the github page says.  I installed via chocolatey as directed.

Then I thought, maybe I'll go to the release folder specifically as indicated in the blog post, and ran the dotnet-script directly from the unzipped folder, and I get the same thing:

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' (x64) was not found.
  - The following frameworks were found:
      6.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

**Comment by seesharper** [comment]
For Chocolatey we don't have the possibility to ship for multiple frameworks as we do in the global tool package. 
The recommended way of installing dotnet-script is `dotnet tool install -g dotnet-script`
