### ISSUE TITLE
dotnet tool install fails without explanation on dotnet 6

### ISSUE THREAD

**Issue by carlin-q-scott** [dotnet-script/dotnet-script#679]
When I try to install the dotnet cli tool globally
> dotnet tool install --global dotnet-script

I get this response:
> Failed to install tool package 'dotnet-script': Access to the path 'C:\Users\me\.dotnet\tools\.store\.stage\yz1gqtsw.afe' is denied.
> Tool 'dotnet-script' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.
> 
> For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

- I installed dotnet-ef globally without issue. 
- I've deleted my tools folder to see if that was the issue, and it was not. 
- I watched the .stage folder during install and it did indeed download and extract the nuget package before failing and deleting the folder.

dotnet --version 6.0.302
dotnet nuget --version 6.2.1.7

**Comment by filipw** [comment]
I am sorry you are running into this but this is a bug in https://github.com/dotnet/sdk and not related to the tool.
It was previously mentioned that this might be due to intermittent problems with Nuget https://github.com/dotnet/sdk/issues/9381#issuecomment-387896853

**Comment by carlin-q-scott** [comment]
They have indeed fixed this issue.
