### ISSUE TITLE
[Linux: Pop_OS 22.04] Updated dotnet-script and am getting Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by MostHated** [dotnet-script/dotnet-script#685]
-- Update
Upon further investigation, it might be a more broad issue, it looks like I am getting a similar error when running powershell scripts outside of my .csx scripts. Ugh... this should be fun.

---

Hey there,
    I updated dotnet-script and my scripts are now giving me "Fatal error. Internal CLR error. (0x80131506)".

I am running Pop_OS 22.04. I don't recall having updated anything else around that time. My Omnisharp has "defaultTargetFramework": "net6.0".  My syslog isn't showing anything while this is happening. I restarted just in case but the same thing is happening. 

Is there anything relatively obvious that might have changed recently that I might have to account for that I might have missed when updating that I need to change in my omnisharp config or similar? Just trying to determine if the issue is actually dotnet-script in the first place. 

I have another script that does my dotnet tools updates and it's output is quite basic. I should probably start keeping track of the version numbers when updates occur to see what might have updated.

<details>
<summary>Update script</summary>

```powershell

#!/usr/bin/pwsh

foreach ($package in $(dotnet tool list --global | select-object -Skip 2)) {
    echo "dotnet tool update --global $($package.Split(" ", 2)[0])"
    dotnet tool update --global $($package.Split(" ", 2)[0])
}

```

</details>

Thanks,
-MH

**Comment by seesharper** [comment]
Thanks and please let us know if this is a problem outside of `dotnet-script` 👍

**Comment by MostHated** [comment]
Yeah, at first I had not seen the error outside of running a csx using dotnet-script, which is of course what made me think it was related off the bat, but that script is doing a number of things, such as calling powershell via `new Process()`. 

Doing some additional tests, I found the following when trying to call pwsh from bash:

```sh

zsh ❯ /bin/pwsh -c "ls"
Fatal error. Internal CLR error. (0x80131506)
[1]    2500627 IOT instruction (core dumped)  /bin/pwsh -c "ls"

~
zsh ✗  /usr/bin/pwsh -c "ls"
Fatal error. Internal CLR error. (0x80131506)
[1]    2505030 IOT instruction (core dumped)  /usr/bin/pwsh -c "ls"

```

I appreciate the links, I will do some looking around in there and see if anything helps. :+1: 
-MH

**Comment by seesharper** [comment]
Great 😃. Closing this for now 👍
