### ISSUE TITLE
dotnet 7 support?

### ISSUE THREAD

**Issue by brad-jones** [dotnet-script/dotnet-script#692]
Just wondering if there are any plans for dotnet 7 support given its now GA.

https://devblogs.microsoft.com/dotnet/announcing-dotnet-7/

**Comment by filipw** [comment]
Yes we will release very soon, the support is already there just based on the RC. 
Once https://github.com/dotnet-script/dotnet-script/pull/693 is merged, we can go.

**Comment by vitaliy-orlov** [comment]
Hi! Any news? I see that #693 has already merged

**Comment by seesharper** [comment]
We are working on the final bits. We will release within the next week

**Comment by seesharper** [comment]
Version 1.4.0 with support for .Net7 has just been released

**Comment by vitaliy-orlov** [comment]
Thanks a lot!
