### ISSUE TITLE
vscode launch file absolute path workaround?

### ISSUE THREAD

**Issue by adamfk** [dotnet-script/dotnet-script#697]
dotnet-script is really, really cool! The only (minor) problem for me is the fixed file path in the `.vscode/launch.json` file.

Is there any chance that the vscode `dotnet script` launch configuration could be improved to not use a user specific absolute path? 

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Script Debug",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "exec",
                "C:/Users/my_username/.dotnet/tools/.store/dotnet-script/1.4.0/dotnet-script/1.4.0/tools/net6.0/any/dotnet-script.dll",
                "${file}"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false
        }
    ]
}
```

I often share `.vscode/launch.json` files (with multiple configurations) for tutorials. It would be really helpful if the person downloading the tutorial could just run it (like a standard c# project) without having to adjust the launch file. The user can't run `dotnet script init` to set the path correctly because there is an existing launch file.

I spent a while trying to get around this by using vscode [variable references](https://code.visualstudio.com/docs/editor/variables-reference), but I think the best I would be able to do is create a custom vscode extension that would just return the correct `dotnet script` path.

Maybe the `dotnet` command could be improved in the future to know the path to `dotnet-script.dll`?

Any other ideas?

Thanks! c# script files are pretty awesome!

**Comment by filipw** [comment]
We generate a better `launch.json` file when we detect that dotnet-script is installed as a global tool. Then it avoids the absolute paths:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": ".NET Script Debug",
      "type": "coreclr",
      "request": "launch",
      "program": "${env:HOME}/.dotnet/tools/dotnet-script",
      "args": ["${file}"],
      "windows": {
        "program": "${env:USERPROFILE}/.dotnet/tools/dotnet-script.exe",
      },
      "cwd": "${workspaceFolder}",
      "stopAtEntry": false,
    }
  ]
}
```

Is it an option for you to use it as global tool?

**Comment by filipw** [comment]
Actually.. looks like your path is really a global tool paths, so maybe the scaffolder has some detection bug. However, you can try the `launch.json` I posted, and if you have a global tool installed it should be enough.

**Comment by adamfk** [comment]
Thanks!!! ❤️  That is so much better than what I had been doing 😝 https://github.com/StateSmith/example-drawio-1/blob/main/.vscode/launch.json#L21

**Comment by adamfk** [comment]
The behavior seems OS specific (Linux generates the good launch.json). Using dotnet-script version 1.5.0 for both windows and WSL2 creates different `init` results. Both installed globally.

windows (not ideal because of absolute path):
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Script Debug",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "exec",
                "C:/Users/user/.dotnet/tools/.store/dotnet-script/1.5.0/dotnet-script/1.5.0/tools/net8.0/any/dotnet-script.dll",
                "${file}"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false
        }
    ]
}
```

WSL2 (good!):
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": ".NET Script Debug",
      "type": "coreclr",
      "request": "launch",
      "program": "${env:HOME}/.dotnet/tools/dotnet-script",
      "args": ["${file}"],
      "windows": {
        "program": "${env:USERPROFILE}/.dotnet/tools/dotnet-script.exe",
      },
      "cwd": "${workspaceFolder}",
      "stopAtEntry": false,
    }
  ]
}
```

Is it worth re-opening the issue to address at some point in the future?

**Comment by filipw** [comment]
Thanks for reporting this - this should fix it https://github.com/dotnet-script/dotnet-script/pull/753
