### ISSUE TITLE
CS0433 erorr

### ISSUE THREAD

**Issue by nczsl** [dotnet-script/dotnet-script#702]
report CS0433 erorr. but i have write full name "System.Data.DataRow"
//
类型“DataRow”同时存在于“System.Data.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”和“System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”中 [console.csx]csharp(CS0433)

![image](https://user-images.githubusercontent.com/5241693/220832969-dde0bc69-efc6-48c3-90a7-b62ab5c670b1.png)

**Comment by filipw** [comment]
can you post the full content of your CSX script?

**Comment by nczsl** [comment]
I know where my problem is coming from because every time I open vscode, a folder called 'net461' is automatically created at a location such as 'C:\Users\hjjls\AppData\Local\Temp\dotnet-script\E\netenv\bofu\Auth'. This is the root of a series of problems I am experiencing because I have not installed any versions other than .NET 7. Therefore, if the script in the .csx file secretly decides to use another version such as net461, then it will produce the series of errors I mentioned earlier. Is there any way to solve this problem? Currently, I can only manually delete it, and deleting net461 can solve the errors such as duplicate assemblies that I mentioned earlier.

**Comment by nczsl** [comment]
I don't want to install any versions other than the latest .NET versions, especially those that are severely outdated. Therefore, I hope there is a solution that can meet my needs. Yes, I don't plan to install duplicate .NET versions on one machine

**Comment by nczsl** [comment]
I further clarified the point in time when net461 was generated, which was the command in vscode: 'After restarting omnisharp

**Comment by nczsl** [comment]
i add sentence '#r "nuget:Microsoft.Data.Sqlite.Core,*"'   then the error is right
