### ISSUE TITLE
Reference to Microsoft.NET.Sdk.Web not work

### ISSUE THREAD

**Issue by i-mark** [dotnet-script/dotnet-script#716]
![CleanShot 2023-04-22 at 12 37 12](https://user-images.githubusercontent.com/28625691/233762806-6040b9de-27bf-48f4-9ba4-f4822e31a4f0.gif)

**dotnet script output**

> error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
> error CS0103: The name 'WebApplication' does not exist in the current context

**dotnet --info output**

> .NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

> Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.203/

> Host:
  Version:      7.0.5
  Architecture: arm64
  Commit:       8042d61b17

> .NET SDKs installed:
  7.0.203 [/usr/local/share/dotnet/sdk]

> .NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by seesharper** [comment]
Try removing the shebang at the top of the script. I think we have a bug parsing the SDK reference

**Comment by charring** [comment]
Any comment at the top of the file will also break the parser:

   //any comment here breaks it

    #r "sdk:Microsoft.NET.Sdk.Web"

    using Microsoft.AspNetCore.Builder;
    using Microsoft.Extensions.Logging;

    var app = WebApplication.Create();

    app.Logger.LogInformation("The app started");

    app.MapGet("/", () => "Hello world");

    app.Run("http://localhost:5178");

Results in errors

   The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

   The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

**Comment by i-mark** [comment]
`#!/usr/bin/env dotnet-script` or `#nullable enable` before `#r "sdk:Microsoft.NET.Sdk.Web"` break the parser.
