### ISSUE TITLE
csx parsing problems

### ISSUE THREAD

**Issue by i-mark** [dotnet-script/dotnet-script#720]
I found a few problems with csx parsing:

1. #load directive with next expression start with string
```csharp
#nullable enable
#load "ScriptHelper.csx"

"Hello world".Dump();
```
Produce error:
`Could not find file '/Users/mark/Code/CSharpLab/ScriptHelper.csx"'.`

Although it works:
```csharp
#nullable enable
#load "ScriptHelper.csx"

;
"Hello world".Dump();
```

2.  using statement without parenthesis or a block on top level
```csharp
using var connection = new SqliteConnection($"Data Source={dbPath}");
```
Produce errors:
`error CS0103: The name 'connection' does not exist in the current context`
`error CS1002: ; expected`

Although it works:
```csharp
void Func()
{
  using var connection = new SqliteConnection($"Data Source={dbPath}");
}
```
3.  [Reference to Microsoft.NET.Sdk.Web not work · Issue #716 · dotnet-script/dotnet-script](https://github.com/dotnet-script/dotnet-script/issues/716)

**Comment by seesharper** [comment]
@atifaziz  Want to take a look at this? 😃

**Comment by atifaziz** [comment]
> @atifaziz Want to take a look at this? 😃

Had a quick look and proposed a fix in PR #724 for the "`#load` directive with next expression start with string" problem.

> 2. using statement without parenthesis or a block on top level

I do believe this is not allowed in a script so not sure anything can be done about it. While not officially documented, see dotnet/roslyn#28588 where it says:

> - test scripting (should disallow using-declaration, maybe some additional complications)

**Comment by i-mark** [comment]
I try to transform my LINQPad queries to dotnet-script. In LINQPad 1, 2 work without problems.

**Comment by atifaziz** [comment]
> I try to transform my LINQPad queries to dotnet-script. In LINQPad 1, 2 work without problems.

LINQPad doesn't use [C# scripting](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Scripting) like this tool so it's not bound by the same restrictions. LINQPad turns your query/script into whole C# programs, very approximately like how I emulate the same in [LINQPadless](https://github.com/atifaziz/LinqPadless).

**Comment by i-mark** [comment]
> > I try to transform my LINQPad queries to dotnet-script. In LINQPad 1, 2 work without problems.
> 
> @i-mark LINQPad doesn't use [C# scripting](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Scripting) like this tool so it's not bound to the same restrictions. LINQPad turns your query/script into a whole C# program, somewhat like what I emulate in [LINQPadless](https://github.com/atifaziz/LinqPadless).

Ok, thx. 

I run it with c# scripting and this code throw (1,11): error CS1002

```csharp
var options = ScriptOptions.Default
		.AddReferences(typeof(Console).Assembly)
		.AddImports("System")
		.AddImports("System.IO");

//var statement = "using (var ms = new System.IO.MemoryStream()) {};";
var statement = "using var ms = new System.IO.MemoryStream();";
await CSharpScript.RunAsync(statement);
```
