### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly

### ISSUE THREAD

**Issue by m4ss1m0g** [dotnet-script/dotnet-script#736]
When I execute this code it raises `FileLoadException`, the issue can be reproduced also in a Docker container.

``` csharp
#r "nuget: NuGet.Packaging, 6.7.0"
#r "nuget: NuGet.Protocol, 6.7.0"

using System.Threading;
using NuGet.Common;
using NuGet.Protocol;
using NuGet.Protocol.Core.Types;
using NuGet.Versioning;

Console.WriteLine("Start");

ILogger logger = NullLogger.Instance;
CancellationToken cancellationToken = CancellationToken.None;

SourceCacheContext cache = new();
```

And the `Dockerfile`

``` dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0

# https://www.nuget.org/packages/dotnet-script/
RUN dotnet tool install dotnet-script --tool-path /usr/bin

WORKDIR /app
COPY main.csx .
ENTRYPOINT [ "dotnet", "script", "main.csx" ]
```

For building the image `docker build -t dotnet-script .` for run `docker run --rm dotnet-script`

**Comment by seesharper** [comment]
Try adding ` --isolated-load-context` when executing the script 👍

**Comment by m4ss1m0g** [comment]
It works thanks.
I attach an interesting article about the [--isolated-load-context](https://www.strathweb.com/2021/09/dotnet-script-1-2-is-out-with-assembly-isolation-feature/) flag
