### ISSUE TITLE
When I use ScriptCompiler compile and run, memory usage not released

### ISSUE THREAD

**Issue by Cricle** [dotnet-script/dotnet-script#747]
The memory took large and no released, my usage is that the process continues to exist but continuously compiles and executes scripts.

When I use `dotnet-script` command in powershell, run `1+1` many many times, will be memroy leak.

**Comment by filipw** [comment]
This is expected. The assemblies can only be collected if you mark ScriptAssemblyLoadContext as collectible

**Comment by Cricle** [comment]
But I use 
```csharp
var loader = new ScriptAssemblyLoadContext(Guid.NewGuid().ToString("N"),true);
var compiler = new ScriptCompiler(logFactory, !options.NoCache)
{
    AssemblyLoadContext = loader
};
```
Call `loader.Unload()` after run. But the memory also not released.

**Comment by Cricle** [comment]
It was ok！
