### ISSUE TITLE
small add to instructions

### ISSUE THREAD

**Issue by Dorian-Grim** [dotnet-script/dotnet-script#758]
Hi. I just spent all day trying to run a `dotnet script` command after installing it with `dotnet tool install -g dotnet-script` and I was getting
```
You must install .NET to run this application.
...
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
...
```
even though `dotnet` is a valid command in my cli. I am using binaries. The only thing that worked is adding `DOTNET_ROOT` to my path with the location of the `dotnet` binaries, even if `Path` already has the location of the `dotnet`

Can somebody please update the readme with this small small detail?

**Comment by filipw** [comment]
Hi, yes let's add it, especially as it could be - as you mentioned - a blocker to get going.

The thing is, this is not really related to dotnet-script itself, it's a mandatory step when manually installing dotnet (that is, not using a package manager) https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install  and also mandatory step when installing .NET into a non-standard location https://learn.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues#runtime-not-found 🙂
